name: Build and Release Java Maven Project

on:
  push:
    branches:
      - master  # 指定你的主要分支，这里假设为 main，可以根据实际情况修改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          cache: maven
      - name: Build Maven project
        run: mvn -B package --file pom.xml

      - name: Upload artifact to release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ github.event.repository.releases_url }}/latest/releases
          asset_path: ./target/valveapi-1.1.0.RELEASE.jar  # 请根据实际情况修改生成的 jar 文件路径
          asset_content_type: application/java-archive
          asset_name: valveapi-1.1.0.RELEASE.jar  # 这里可以根据需要修改 artifact 的名称，这里假设以 git SHA 作为版本号

